services:
  db:
    image: postgres:17.5-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    # volumes:
    #   - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

# volumes: # db_data:
